/**
 * Lote de recomendações de estrelas da FORÇA-TAREFA (18/08/2026) — dado, não código.
 *
 * De onde veio: o pipeline do JV que roda FORA do app (7 avaliadores por cluster de área →
 * calibrador que reescala na curva real da base → revisor adversarial que tenta refutar toda
 * nota ≥3). São 99 projetos que aguardavam decisão. A distribuição final — 0★:8 · 1★:43 ·
 * 2★:40 · 3★:6 · 4★:2 — é o retrato de uma régua dura: nenhum chegou a 5.
 *
 * Por que como SEED e não por importação autenticada: o edge exige OAuth em toda rota, e um
 * lote que só entra com cookie de sessão válido não chega à produção sozinho. Aqui ele viaja
 * junto do deploy, igual ao `FAQ_SEED`.
 *
 * ⚠️ **O seed só INSERE o que falta — nunca sobrescreve.** A recomendação do agente
 * classificador (peça 4) e qualquer reavaliação valem mais que este retrato: um seed que
 * atualizasse desfaria, a cada deploy, a leitura mais nova.
 *
 * ⚠️ Isto NÃO é nota: nada aqui toca a coluna "Estrelas" da planilha. É sugestão + a leitura
 * que a justifica, e quem grava é o clique de gente na tela.
 */
export type SementeAvaliacao = {
  projeto_id: string;
  estrelas_recomendada: number;
  confianca: 'alta' | 'media' | 'baixa';
  leitura: string | null;
  contestada: boolean;
};

/** Carimbo de origem gravado em cada linha semeada (aparece no rodapé da recomendação). */
export const ORIGEM_SEED_FORCA_TAREFA = 'forca-tarefa-jv-18-08';

export const AVALIACOES_SEED: SementeAvaliacao[] = [
  { projeto_id: "625248d60d3858b8d808da3089d83544", estrelas_recomendada: 2.0, confianca: "media", leitura: "Recorrência semanal, IA no fluxo e app publicado como ponteiro sustentam a faixa 2. Não sobe porque repete o escopo do [ILUSTRA] (já 3) e serve um time só. Para subir: nomear ponteiro de uso e diferenciar do [ILUSTRA].", contestada: false },
  { projeto_id: "legado-141", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Recorrência real de solicitações, mas sem ponteiro nomeado no memorial e com 75h/mês sinalizadas como altas pela própria auditoria. Âncora direta: Regularizações - GoGroup (escopo maior) = 1.", contestada: false },
  { projeto_id: "LEGADO-185", estrelas_recomendada: 1.0, confianca: "media", leitura: "Contrafactual confirmado pelo líder, mas memorial de 1 linha e nenhuma base ou painel onde conferir a ruptura evitada: piso. Nomear o ponteiro sobe direto para 2.", contestada: false },
  { projeto_id: "legado-203", estrelas_recomendada: 2.0, confianca: "media", leitura: "Painel com URL própria usado por Produto e diretoria: mesma faixa de Godash, Damidash e V.I.S.I.O.N. (2). Atualização sob demanda (sem cron) e memorial financeiro inconsistente impedem mais.", contestada: false },
  { projeto_id: "legado-229", estrelas_recomendada: 1.0, confianca: "media", leitura: "Mantida a nota do bench: recorrência diária e dashboard nomeado, mas ponteiro é KPI genérico, escopo de 1 analista/1 área e as 121h/mês declaradas são implausíveis.", contestada: false },
  { projeto_id: "legado-263", estrelas_recomendada: 1.0, confianca: "media", leitura: "IA generativa com uso recorrente pelo comercial B2B, mas sem ponteiro nomeado onde conferir e com memorial replicando o mesmo bloco de 15h em 4 cargos. Horas não pontuam: piso.", contestada: false },
  { projeto_id: "e4b1dcc3e07f56a7f576c672fcc78824", estrelas_recomendada: 4.0, confianca: "alta", leitura: "Confirma o 4 do bench: plataforma de AVD para 3 empresas e 300+ colaboradores, ciclo semestral, RBAC e integrações nomeadas. Interna a uma área e ainda pendente, não sobe a 5.", contestada: false },
  { projeto_id: "95cbd504a32e6f29cf5549ad1a16ae53", estrelas_recomendada: 2.0, confianca: "media", leitura: "Rebaixado: o escopo sobrepõe o CTR machine já pontuado (7) e a âncora Máquina de Criação de CTRs vale 2; não há ponteiro nomeado de execuções e o valor citado é projeção de hit. Delimitar escopo e nomear ponteiro reabre o 3.", contestada: false },
  { projeto_id: "797a887e1fcba72cf7da73c9dfffa81a", estrelas_recomendada: 3.0, confianca: "media", leitura: "Confirma o 3 já registrado na base: IA no resumo diário, KPI/SLA antes inexistente e adoção pela gestão do time. Mantido por consistência; sem memorial, é nota de partida.", contestada: false },
  { projeto_id: "2afc53e51f6935703b474988d0840a4a", estrelas_recomendada: 3.0, confianca: "media", leitura: "Confirma o 3 da base: IA sugere e publica comentários em escala, uso diário e salto de patamar. Ponteiro só qualitativo limita a subida; tratar o risco de segurança apontado.", contestada: false },
  { projeto_id: "1201f1b825c691c3e463efc27aa3fc57", estrelas_recomendada: 2.0, confianca: "media", leitura: "O formulario diz alguem_fazia = nao e o memorial cobra 25h/mes de rotina manual 'equivalente estimada': baseline contraditorio, como em legado-256 e Vencimentos UNILOG. Ponteiro e alerta em chat, escopo de 1 marca e 1 time.", contestada: true },
  { projeto_id: "141a54f898a2a2bc781eb150d280ca98", estrelas_recomendada: 2.0, confianca: "media", leitura: "Histórico persistido e auditável no Metabase, cadência semanal por marca e uso da liderança no fechamento: sólida. Determinístico, 1 analista e horas infladas seguram em 2.", contestada: false },
  { projeto_id: "88a169cce620725c413d7457b3cb9ce1", estrelas_recomendada: 1.0, confianca: "alta", leitura: "Alerta simples em Chat, ganho de cerca de 10 min/mês por pessoa e sem painel ou relatório nomeado — o próprio memorial admite. Mesma faixa de todas as âncoras de alerta em Chat (1).", contestada: false },
  { projeto_id: "094f30c93878a4211fe047de14def297", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Rotina real de expedição com assinatura de motorista/conferente e PDF no Drive, mas sem memorial e com o rótulo de especial pouco sustentado: nota de partida no piso.", contestada: false },
  { projeto_id: "d371ae8b46b8b79a2bf3b5615c46ef95", estrelas_recomendada: 2.0, confianca: "media", leitura: "Cron diário, IA no fluxo e base oficial de FAQs das 8 marcas com validação humana: sólida. Sem evidência do ponteiro de resolução do bot e com memorial contestado pelo líder, não sobe.", contestada: false },
  { projeto_id: "f8c9e95980b86a7ab3f7ab2a6ecde82f", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Rebaixado: sem evidência de adoção e com doc técnica incompleta, falta o ponteiro que a faixa 2 exige. Padronizar prompt de 5 marcas e destravar conhecimento tácito é valor real: registrar uso sobe de novo.", contestada: false },
  { projeto_id: "0c126bc37f8d5b9ed16a6ceb7aa8f61b", estrelas_recomendada: 3.0, confianca: "media", leitura: "Memorial ausente, nenhum ponteiro nomeado e escopo de uma area (Growth). Faixa 4 exige multi-area, risco material ou ponteiro auditavel; aqui o valor e narrativo e chega via apps derivados, um deles submetido a parte pelo mesmo autor.", contestada: true },
  { projeto_id: "7cc5e99cdc78654b7baa2717ac9eb6ca", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Centralizar catálogos serve B2B e Produto, mas é vitrine simples, sem IA, sem recorrência automática e sem nenhum ponteiro de acesso ou uso: piso, como os portais simples da base.", contestada: false },
  { projeto_id: "5760091fa8ea81b8f3cd8bd9234968b8", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Rebaixado: sem ponteiro verificável e com doc técnica incompleta, a faixa 2 (recorrente + ponteiro + time inteiro) não se sustenta. Volta a 2 nomeando onde conferir as pautas geradas e o uso pelo time.", contestada: false },
  { projeto_id: "2e7661ed9d40c55958cb7cff0402c893", estrelas_recomendada: 2.0, confianca: "media", leitura: "Painel recorrente e verificável de 8 marcas que sustenta o report ao board: faixa 2, igual a Godash, Damidash e V.I.S.I.O.N. Sem IA nem autonomia, não chega a prata.", contestada: false },
  { projeto_id: "892919afc3baf2542791fe2d87817809", estrelas_recomendada: 2.0, confianca: "media", leitura: "Margem/CMV por SKU nas 8 marcas com refresh automático e histórico congelado: ponteiro auditável, faixa 2 dos painéis. Sem inteligência no fluxo, não vai a 3.", contestada: false },
  { projeto_id: "88ba535dbdf3d55b708832576b536e9f", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "É essencialmente uma base de avaliação com dashboard, sem memorial nem ponteiro nomeado e com recorrência baixa (reavaliações periódicas): piso, apesar do valor de reduzir dependência de pessoas.", contestada: false },
  { projeto_id: "29899445b2da1e827d277f8bf72fdd37", estrelas_recomendada: 2.0, confianca: "media", leitura: "Ponteiros nomeados (painel + base do DP + planilha), alcance de toda a empresa e prova documental de compliance com report à Diretoria: sólida. Stack simples e sem IA em runtime seguram em 2.", contestada: false },
  { projeto_id: "daaf2bf65b49579604a4510b07b9b9f2", estrelas_recomendada: 1.0, confianca: "media", leitura: "O memorial admite ausência de cron/webhook: os dados vêm de JSON com atualização manual, falhando a recorrência automática. Alcance multi-time e honestidade contam a favor quando automatizar.", contestada: false },
  { projeto_id: "e57b287a0fa5c3abfb815d13d5f3c556", estrelas_recomendada: 3.0, confianca: "media", leitura: "Prata como o GDI: redesenho real do fluxo de expedição, 1000 itens/dia quitados no Chaplin por bipagem, rastro por operador e o mesmo volume passando de 10 para 7 auxiliares.", contestada: false },
  { projeto_id: "0948b36da6660fa70fe4e4337c46e652", estrelas_recomendada: 2.0, confianca: "media", leitura: "Laudo rastreável por pedido, máquina e SKU decidindo liberar ou barrar o lote, usado em todos os turnos: sólida. Especial honesto ao não inventar refugo evitado, mas sem memorial não sobe.", contestada: false },
  { projeto_id: "585bf5b9dbb412ca995a88d8a22b3def", estrelas_recomendada: 1.0, confianca: "media", leitura: "RPA real (Playwright) 3x/dia em Titan e CorpEM, mas atende a rotina de 1 supervisor (5,5h/mês) em 1 time, sem ponteiro além da base master: piso.", contestada: false },
  { projeto_id: "84145328d7589246ece6f3782a729b28", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Bloquear lote de tinta vencido é controle preventivo real, mas não há memorial, ponteiro nomeado nem evidência de uso, e é um de 4 apps do mesmo padrão do autor: piso.", contestada: false },
  { projeto_id: "9a71f410d3289dddd51e4a33acc2989d", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Rebaixado: sem ponteiro e sem adoção comprovada em 12 dias, a faixa 2 não se sustenta apesar da IA agêntica e da recomendação Adiantar/Atrasar/Manter. Contexto especial honesto; registrar uso e ponteiro sobe.", contestada: false },
  { projeto_id: "a016d911ab714cb2fb7d0f4478b7025d", estrelas_recomendada: 2.0, confianca: "media", leitura: "O resultado e declarado como 'esperado' - vagas fora do SLA ainda nao medidas. Ponteiro e alerta no Google Chat, 20 dias sem adocao auditada, uma area so e memorial com o bloco de analista senior repetido.", contestada: true },
  { projeto_id: "ba4e5bef40d8a25f0447e12fec736f92", estrelas_recomendada: 2.0, confianca: "media", leitura: "Cron diário com ação aprovada em um clique, integrando 4 sistemas em 6 marcas: sólida. Falta contar os casos de order bump evitados para disputar o 3.", contestada: false },
  { projeto_id: "4f452f2a1ef198a4d672c78485581da8", estrelas_recomendada: 3.0, confianca: "media", leitura: "Sem memorial, contrafactual nao preenchido (a propria auditoria aponta) e 19 dias de vida; o acompanhamento pela diretoria e os R$ 4,8M sao 'resultado esperado'. A cobertura 55,7%->90,4% sustenta prata, nao prata alta.", contestada: true },
  { projeto_id: "7bdf437fa8b64f44c7f148514844ffa8", estrelas_recomendada: 0.0, confianca: "media", leitura: "Zerado por comparabilidade: é peça de vaga única, o mesmo caso da Pesquisa Prima Vida (0). Painel /admin, CSV e trilha existem, mas sem recorrência não pontua; reaproveitar em novas vagas muda a nota.", contestada: false },
  { projeto_id: "9cede95b8da4fbbaf68e75e84491ea29", estrelas_recomendada: 0.0, confianca: "media", leitura: "Mantido em 0: o próprio memorial declara ciclo único e a rastreabilidade é fraca. Painel de resultados nomeado não substitui recorrência comprovada.", contestada: false },
  { projeto_id: "39553b210705e924902ed6eb95cb320a", estrelas_recomendada: 2.0, confianca: "media", leitura: "Chatbot com IA em runtime para todos os colaboradores, uso contínuo e contrafactual claro: entrega mais que a âncora GABI (1). Ponteiro indireto (registros do Request) impede a prata.", contestada: false },
  { projeto_id: "cccccfd86433071aa5c310bef548c022", estrelas_recomendada: 1.0, confianca: "media", leitura: "Ponteiro e log nomeados (planilha Controle Ressarcimento, Drive) e trava anti-duplicidade são bons, mas a frequência é de 2x/mês e o escopo é de uma assistente: piso.", contestada: false },
  { projeto_id: "c417fe024caf2b48b5701b82070b34b9", estrelas_recomendada: 1.0, confianca: "media", leitura: "Memorial honesto e ponteiro nomeado (aba Status, coluna Alerta Troca de Cor), mas alcance de 1 a 2 pessoas e execução assistida por TOTP, sem cron: piso. Automatizar o gatilho sobe para 2.", contestada: false },
  { projeto_id: "85d3a9d728fdb909f0b2b290d37b7d88", estrelas_recomendada: 0.0, confianca: "baixa", leitura: "Zerado: o valor está no futuro ('poderá ser consultável'), sem memorial, sem consumidor nomeado e com cadastro operacional incompleto — não há uso recorrente a pontuar. Nomear o primeiro consumidor real reabre a nota.", contestada: false },
  { projeto_id: "66e286edd711576d3b13e51f97f918d5", estrelas_recomendada: 2.0, confianca: "media", leitura: "Recorrente (55 envios/mês), painel e CSV conferíveis e KPI de área (NPS do processo), servindo R&S e liderança: sólida. Determinístico e de escopo de um time: 2.", contestada: false },
  { projeto_id: "1387ecb575c9668970b74a384feee1c1", estrelas_recomendada: 2.0, confianca: "media", leitura: "Risco jurídico real (PEP/conflito de interesse), cerca de 50 declarações/mês, protocolo e painel auditáveis em duas áreas (RH e Compliance). Falta IA ou autonomia para chegar a 3.", contestada: false },
  { projeto_id: "c8b49c47e4e99cf25aa0af79be78d32e", estrelas_recomendada: 2.0, confianca: "media", leitura: "Duplicidade: o proprio memorial abre com 'O Argos e uma plataforma de CDP e segmentacao' - e o mesmo produto de Argos - CDP inteligente, do mesmo autor, ja pontuado em 3. Pago o par uma vez; resta o valor da camada de agente na Insider.", contestada: true },
  { projeto_id: "f075deb74219cab44640b44ef71d486c", estrelas_recomendada: 2.0, confianca: "media", leitura: "Dashboard em produção com URL e abas verificáveis e IA embarcada comentando variações, com aba de Revisão FP&A: sólida. Cadência mensal e alcance Ops + FP&A seguram em 2.", contestada: false },
  { projeto_id: "a8d2545f3072c88da9c8d2681f71a231", estrelas_recomendada: 2.0, confianca: "media", leitura: "Substitui Goal Seek em Excel/VBA por calculadora web usada por Vendas B2B e Cadastro, padronizando margem mínima por marca: sólida. A IA só entra como fallback de busca, sem prata.", contestada: false },
  { projeto_id: "2c23b6650cf58226cf7414867764fcae", estrelas_recomendada: 2.0, confianca: "baixa", leitura: "Substitui controle em papel em 16 máquinas com janelas de 1-3h, rastreabilidade por turno/auditor/cor e ranking de conformidade: recorrência alta e risco de qualidade evitado. Sem ponteiro externo, fica em 2.", contestada: false },
  { projeto_id: "8f315702b9f3ea3f20e9d1fc104a1d1f", estrelas_recomendada: 2.0, confianca: "baixa", leitura: "Bot de não conformidade no Google Chat dá rastro externo verificável e tratativa imediata da liderança, com recorrência por turno em 3 setores: sólida. Falta memorial formal para disputar prata.", contestada: false },
  { projeto_id: "1eac04cf4319ff23855348f85f0529e4", estrelas_recomendada: 2.0, confianca: "media", leitura: "Subavaliado: e o DWH nomeado a montante de VERSTA (8), GoPilot (4) e Dashboard de Planejamento, com crons, intraday e backfill e ~10 usuarios. Mesma forma do Argos; sem ponteiro no cadastro, sobe so a 2.", contestada: true },
  { projeto_id: "8aed1235aad8d630c5cf3535f3fe969e", estrelas_recomendada: 1.0, confianca: "media", leitura: "Rebaixado: submetida há 1 dia, sem histórico de adoção, e o painel apontado mede resultado comercial, não o ponteiro declarado. Sync via cron e IA sobre a carteira são bons — reavaliar com uso registrado.", contestada: false },
  { projeto_id: "78cab6ebfceed6820926743bcc658e62", estrelas_recomendada: 4.0, confianca: "alta", leitura: "Faixa 4: DAG diária mais RPA em painel com CAPTCHA, 8 marcas, risco material (fraude e prazo de defesa) e ponteiro auditável nomeado, com 11.149 processos e 0 falhas em 30 dias. Melhor evidência do lote.", contestada: false },
  { projeto_id: "7363ac724047eaba4b2de065f171ec82", estrelas_recomendada: 1.0, confianca: "media", leitura: "Âncora direta: escopo praticamente igual ao Controle de Checklist Fechamento Contábil (1). Serve 2 a 4 pessoas, parte do trabalho segue manual dentro do portal e o líder ainda não validou.", contestada: false },
  { projeto_id: "ae06cf9cbd5f27797016e031658989f7", estrelas_recomendada: 2.0, confianca: "media", leitura: "A auditoria afirma que a rastreabilidade do ponteiro nao foi comprovada com indicador nomeado; sem memorial, 13 dias e ganho 'esperado'. Mesmo tratamento do Gohelp (alcance externo sem ponteiro) = 2. Id correto do alvos.json.", contestada: true },
  { projeto_id: "7a3ef686723282015de5b5e20b4a43f1", estrelas_recomendada: 1.0, confianca: "media", leitura: "Piso por duplicidade: é o gêmeo do painel Gocase do mesmo autor, com ganho idêntico. Pontuo o par uma vez (Gocase = 2) para não pagar duas vezes o mesmo produto.", contestada: false },
  { projeto_id: "ae6af3b0bcfcff0bc47322c0a37547f4", estrelas_recomendada: 1.0, confianca: "media", leitura: "Encanamento confiável com cron real 2x/dia, mas o ganho próprio é pequeno (3h/mês) e o entregável é infraestrutura. Nomear as automações de Produto e Supply que consomem a base sobe para 2.", contestada: false },
  { projeto_id: "c508f9083c801d5b6fbc982339599c27", estrelas_recomendada: 2.0, confianca: "media", leitura: "Elevado para alinhar com Godash, Mix e CMV (2): publicação automatizada 2x/dia via GitHub Actions/Cloudflare, acesso por link no domínio e KPIs nomeados. Pontuo este como par principal; o gêmeo Gobeaute fica em 1.", contestada: false },
  { projeto_id: "5fa4f6433d0a3306208238da7797e20b", estrelas_recomendada: 1.0, confianca: "media", leitura: "Rebaixado: uso mensal substituindo a rotina da própria autora cai na regra explícita de piso da régua; o ponteiro é derivado do V.I.S.I.O.N. e o papel da IA não está claro. Alinha com o Fórum de melhoria contínua.", contestada: false },
  { projeto_id: "c4c87bd816245d0f1f998a5cbc226721", estrelas_recomendada: 2.0, confianca: "alta", leitura: "Ciclo mensal (reuniao de pauta), 3,5h/mes somando 7 pessoas e 12 dias de vida sem adocao registrada. O unico ponteiro nomeado (GA/Insider, receita e CTR) nao mede este projeto. Mesmo criterio do 9a71f410, tambem com 12 dias.", contestada: true },
  { projeto_id: "0769139235f84f76040a35d78107d0fc", estrelas_recomendada: 2.0, confianca: "media", leitura: "Ponteiro realmente auditável (aba Estatísticas e API de stats) e uso recorrente, mas a IA não decide nada e o alcance é de um time: faixa 2.", contestada: false },
  { projeto_id: "4808022d3cefd3215c5ae44dd57e5187", estrelas_recomendada: 1.0, confianca: "media", leitura: "Export manual do Monday mais prompt no Claude para a rotina da própria autora, 4x/mês e 1 pessoa; o memorial admite que não há painel para conferir. Nada roda sozinho: piso.", contestada: false },
  { projeto_id: "d8980d2591eba0efa9d0cccb13cf0972", estrelas_recomendada: 1.0, confianca: "media", leitura: "Mesmo board e mesmo mecanismo do Daily, uso individual 4x/mês e sem relatório nomeado para verificar: piso. Consolidar Daily e Semanal em um projeto evita contagem dupla.", contestada: false },
  { projeto_id: "47048111d82a03b727c832e673673ea6", estrelas_recomendada: 1.0, confianca: "alta", leitura: "É a âncora exata de 1 estrela: rotina mensal de 30 min de 1 analista, ponteiro bem definido na aba Histórico e líder confirmando que não move KPI. Automação limpa e honesta, mas local.", contestada: false },
  { projeto_id: "c19b41ebd28f92560f5c8c826aaa4389", estrelas_recomendada: 2.0, confianca: "media", leitura: "7 dias de vida e o memorial admite que nao existe relatorio anterior consolidado; o Clind apenas 'da nocao do volume'. 108h/mes tiradas de 2 pessoas e inflado. Mesmo criterio aplicado a Haileydash e Color Drop (2).", contestada: true },
  { projeto_id: "452ee30f320161450960537cf1594cb1", estrelas_recomendada: 1.0, confianca: "media", leitura: "Cron diário no n8n e visões nomeadas para conferência são recorrência real, mas o alcance é de 1 assistente em 1 time, com 7,5h/mês e descrição rasa: piso.", contestada: false },
  { projeto_id: "12d5f2bcbd0cefad63af4a76d7f2dae9", estrelas_recomendada: 2.0, confianca: "media", leitura: "IA em etapa concreta (máscara, lote, avaliação) em produção com o dashboard Portfólio como ponteiro, mas o ganho fica dentro de um time: mesma faixa do Gerador de Vistas (2).", contestada: false },
  { projeto_id: "5afa214f38acc42a1a5a377bc15650d1", estrelas_recomendada: 2.0, confianca: "media", leitura: "Rotina fiscal recorrente de 45 mil XMLs/mês em produção com log de erros nomeado: mesma faixa da Automação de Extratos Bancários (2). Horas sem fonte corporativa impedem subir.", contestada: false },
  { projeto_id: "9512d433f168a6eb0804e5b543cdb5fe", estrelas_recomendada: 2.0, confianca: "media", leitura: "Rebaixado para a faixa dos painéis multi-marca (Mix e CMV Gobeaute = 2, com refresh automático): aqui o build ainda é manual, falhando a recorrência automática. Contrafactual nomeado é forte — automatizar o refresh reabre o 3.", contestada: false },
  { projeto_id: "ebc8d37eca84c66f4c0579f4253f9590", estrelas_recomendada: 1.0, confianca: "media", leitura: "A IA de extração de PDFs é real e a recorrência mensal existe, mas atende 1 analista e move cerca de 1,6h/mês: automação de rotina própria de baixa frequência = piso.", contestada: false },
  { projeto_id: "546988880104067db81665f63481eca1", estrelas_recomendada: 2.0, confianca: "baixa", leitura: "ROI ao vivo de 6 marcas conferido linha a linha contra o Metabase: faixa 2 dos painéis, como Damidash. Seis dias de vida e doc formal fraca impedem prata; reavaliar com histórico de uso.", contestada: false },
  { projeto_id: "ccedc03371ef0864ceadc99472dd9b00", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Rebaixado: parte dos dados é estática, a recorrência é de consulta e não há adoção comprovada — falham dois requisitos da faixa 2. A decisão contratual é de alto valor: com uso registrado volta a 2.", contestada: false },
  { projeto_id: "3ed3db78fa3465c4d6fe88f2ee44e113", estrelas_recomendada: 0.0, confianca: "baixa", leitura: "Zerado: o memorial aponta um domínio e o código enviado é de outro projeto, então nem ponteiro nem fluxo de IA são conferíveis, e o escopo sobrepõe o Direcionador de Fórum. Requer ressubmissão coerente.", contestada: false },
  { projeto_id: "55907590ea78bf1f72441c3236dfb4b5", estrelas_recomendada: 2.0, confianca: "media", leitura: "IA recolore por receita e publica no Meta, com agentlog como ponteiro, atendendo Produto e Growth. Com 3 dias de vida, recorrência e volume são promessa — reavaliar com histórico.", contestada: false },
  { projeto_id: "4d1e0abf61a2e18d7fd3ef261a7f90ae", estrelas_recomendada: 2.0, confianca: "media", leitura: "Desenho sólido: 2 crons diários, IA agrupando evidências e alerta ativo no Chat em 2 marcas. Com 2 dias de vida a adoção não está provada — reavaliar em 30 dias com uso registrado.", contestada: false },
  { projeto_id: "5071c7c3b92bf98fb2e50e8e987ae091", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Um dia de vida, sem histórico de uso, saving estimado sem controle formal e escopo praticamente sobreposto ao Radar Preventivo de SLA do mesmo time: piso. Avaliar fusão em vez de pontuar duas vezes.", contestada: false },
  { projeto_id: "4f76f2758b1e666d5589c7df4327c7f0", estrelas_recomendada: 2.0, confianca: "media", leitura: "Rebaixado pelo mesmo critério aplicado aos recentes (Color Drop, Carteira de clientes, Pacote de Dados): a adoção nas 3 áreas ainda não foi auditada. Ponteiro duplo (horas e custo de compra) é bom sinal — auditar o uso reabre o 3.", contestada: false },
  { projeto_id: "312330b0d164b011e1dfe8c897eb5b69", estrelas_recomendada: 2.0, confianca: "media", leitura: "Ritual recorrente (cerca de 10 lives/mês) com memorial coerente e contrafactual confirmado pelo líder: sólida. Tempo apenas por relato e alcance de um time seguram em 2.", contestada: false },
  { projeto_id: "85bde7847eca496f6ecda453171406b8", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Baseline hipotético (ninguém fazia), memorial contando ganho trimestral como mensal e saving atribuído a um fluxo Claude ausente da doc técnica: piso até o memorial ser corrigido.", contestada: false },
  { projeto_id: "65601548187c5228fc6004ad9f8e047d", estrelas_recomendada: 2.0, confianca: "media", leitura: "Cobre lacuna real do Protheus na escrituração de CT-es (170 mil XMLs/mês) e o valor está no risco fiscal evitado: sólida. Linha de base estimada e correções pendentes seguram em 2.", contestada: false },
  { projeto_id: "b299eaa87a2bd3d8a25168d98301cbc6", estrelas_recomendada: 1.0, confianca: "media", leitura: "Piso confirmado: o próprio líder nega o contrafactual e o alcance é de 2 pessoas. Cron diário não compensa a ausência de ponteiro nem o alcance mínimo.", contestada: false },
  { projeto_id: "edb6bc16201a7168bb26dd45496225b7", estrelas_recomendada: 1.0, confianca: "media", leitura: "Âncora direta na base: Regularizações - GoGroup, de escopo maior, vale 1. Volume pequeno (49 documentos) e rastreabilidade apontada como ponto fraco mantêm no piso.", contestada: false },
  { projeto_id: "1d45f9dd9966de3d6ac5716b9f7a7455", estrelas_recomendada: 2.0, confianca: "media", leitura: "IA na triagem, digest a cada 2h e ponteiros nomeados (Painel Gerencial Dados, NPS de Dados): sólida. É instrumentação da própria área, com 5 dias de vida e adoção externa não comprovada.", contestada: false },
  { projeto_id: "c6aa8db232c4d1ab796de245a713a466", estrelas_recomendada: 1.0, confianca: "media", leitura: "Monitores recorrentes reais, mas o rastro vive só no histórico do Chat, sem antes x depois consolidado, e substitui a investigação do próprio time de Dados: piso.", contestada: false },
  { projeto_id: "a0be9dd2308bb3491a70e27dd5a54d10", estrelas_recomendada: 2.0, confianca: "media", leitura: "IA gera deck, resumo e cards com artefatos semanais verificáveis (output/ANO-Wsemana, test-cards) consumidos pelo time de CRO: sólida. Sem ponteiro de horas nomeado, não passa de 2.", contestada: false },
  { projeto_id: "7a94c4d4fffe1eee52b51bb6cd5a88ad", estrelas_recomendada: 3.0, confianca: "media", leitura: "Prata pelo contrafactual máximo (sem ele a loja para de vender) e execução madura em produção, com log, auditoria e dashboard como ponteiro. Uma marca só e sem IA travam em 3; completar os campos do memorial.", contestada: false },
  { projeto_id: "LEGADO-095", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "O entregável é o próprio relatório diário, sem ponteiro verificável nem contrafactual nomeado e com doc não lida; Reenvio Pendente. A evidência atual sustenta apenas o piso.", contestada: false },
  { projeto_id: "LEGADO-098", estrelas_recomendada: 1.0, confianca: "media", leitura: "Mantido no piso: recorrente e com volume real de chargebacks, mas é preenchimento de dados sem IA, restrito ao próprio time e com doc inacessível. Coerente com os pares de CX.", contestada: false },
  { projeto_id: "LEGADO-102", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Ganho pequeno e local, sem IA e sem painel nomeado, com doc inacessível e Reenvio Pendente: piso. Nomear onde conferir as ocorrências consolidadas é o próximo passo.", contestada: false },
  { projeto_id: "LEGADO-104", estrelas_recomendada: 2.0, confianca: "media", leitura: "Cadência de 10min com regra anti-falso-positivo (3 intervalos) e doc completa e versionada, servindo o time e não só o autor: sólida. Reenvio Pendente impõe o teto de 2.", contestada: false },
  { projeto_id: "LEGADO-103", estrelas_recomendada: 1.0, confianca: "media", leitura: "IA redige, humano publica e o entregável para na planilha, com doc inacessível. O viés reputacional do Reclame Aqui não basta para sair do piso sem ponteiro verificável.", contestada: false },
  { projeto_id: "LEGADO-100B", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Classificação diária útil, mas o alcance é uma conferência do próprio time, sem ponteiro nomeado nem contrafactual descrito; doc inacessível e Reenvio Pendente: piso.", contestada: false },
  { projeto_id: "LEGADO-100A", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "O entregável é o próprio slide, uso mensal por 4 pessoas e sem ponteiro além do tempo declarado; doc inacessível e Reenvio Pendente: piso.", contestada: false },
  { projeto_id: "LEGADO-118", estrelas_recomendada: 0.0, confianca: "baixa", leitura: "Mantido em 0: memorial insuficiente, inconsistência irreconciliável (valor declarado cerca de 60x o máximo possível), status em branco e doc inacessível. Só volta a pontuar com ressubmissão.", contestada: false },
  { projeto_id: "LEGADO-164", estrelas_recomendada: 0.0, confianca: "baixa", leitura: "Zerado: memorial reduzido à conta de R$, descrição de uma frase, sem ponteiro, sem contrafactual e sem evidência de execução recorrente, em Reenvio Pendente. Ressubmeter com doc e ponteiro.", contestada: false },
  { projeto_id: "LEGADO-187", estrelas_recomendada: 0.0, confianca: "baixa", leitura: "Mantido em 0: descrição de uma linha, memorial de uma conta (4h x R$25), sem ponteiro, sem contrafactual e sem quem consome o alerta, em Reenvio Pendente.", contestada: false },
  { projeto_id: "LEGADO-192", estrelas_recomendada: 0.0, confianca: "baixa", leitura: "Mantido em 0: documentação nula (descrição de uma linha, memorial só 20h x R$55,15), sem ponteiro, sem contrafactual e sem descrição do fluxo. Teto de 2 se refizer.", contestada: false },
  { projeto_id: "LEGADO-193", estrelas_recomendada: 1.0, confianca: "media", leitura: "Mantida a nota da base: automação n8n recorrente mas local, memorial reduzido a horas x custo e status Reenvio Pendente (teto de 2).", contestada: false },
  { projeto_id: "legado-256", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Cron diário e curva ABC versionada são recorrência real, mas o memorial não nomeia ponteiro e contradiz o formulário (alguém fazia = não, contra 23h/mês de analista); Reenvio Pendente: piso.", contestada: false },
  { projeto_id: "cddae49aba75b90af7f210ac5a2c4073", estrelas_recomendada: 2.0, confianca: "media", leitura: "Governança de 841 fluxos nas 4 instâncias, JSON versionado no GitHub e criticidade classificada por IA valeriam mais, mas Reenvio Pendente fixa o teto em 2. Refazer a doc destrava a nota.", contestada: false },
  { projeto_id: "51e9e6688c428027257542b7f71f666b", estrelas_recomendada: 1.0, confianca: "media", leitura: "Mantida a nota da base: dash recorrente dos 7 sites, mas doc muito incompleta, sem memorial e com classificação especial inconsistente — comporta-se como dash padrão de consolidação.", contestada: false },
  { projeto_id: "fd40aab38a81793e733273e9bb684597", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Sem memorial de cálculo (ponteiro ausente) e em Reenvio Pendente, com teto de 2; o enquadramento como especial não se sustenta — comporta-se como automação padrão de cadastro.", contestada: false },
  { projeto_id: "05c4b3690bb33ff8f9bc0c039790d971", estrelas_recomendada: 2.0, confianca: "baixa", leitura: "Usuários fora do time (fornecedor), AQL e NC rastreáveis e apoio a ressarcimento e seguro valeriam prata; Reenvio Pendente e ausência de memorial fixam o teto em 2.", contestada: false },
  { projeto_id: "a2172a9ff26a6a26cdd073b91efdb86d", estrelas_recomendada: 1.0, confianca: "baixa", leitura: "Landing pages de cadastro B2B com validação de CNPJ e entrega no RD Station: recorrente e replicável por marca, mas sem memorial, e o ganho declarado é substituir um SDR — custo, que a régua não premia. Reenvio Pendente.", contestada: false },
];
