/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmeterRouteImport } from './routes/submeter'
import { Route as MeusProjetosRouteImport } from './routes/meus-projetos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as ProjetoIdRouteImport } from './routes/projeto.$id'
import { Route as EditarIdRouteImport } from './routes/editar.$id'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedInvestigadorRouteImport } from './routes/_authenticated/investigador'
import { Route as AuthenticatedFluxosRouteImport } from './routes/_authenticated/fluxos'
import { Route as AuthenticatedEspeciaisRouteImport } from './routes/_authenticated/especiais'
import { Route as AuthenticatedEmailLegadosRouteImport } from './routes/_authenticated/email-legados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedAprovacoesPendentesRouteImport } from './routes/_authenticated/aprovacoes-pendentes'
import { Route as AuthenticatedAglutinacaoRouteImport } from './routes/_authenticated/aglutinacao'
import { Route as AuthenticatedTestesRouteRouteImport } from './routes/_authenticated/testes/route'
import { Route as FaqCategoriaIndexRouteImport } from './routes/faq.$categoria.index'
import { Route as AuthenticatedTestesIndexRouteImport } from './routes/_authenticated/testes/index'
import { Route as FaqCategoriaItemRouteImport } from './routes/faq.$categoria.$item'
import { Route as AuthenticatedTestesPromptsRouteImport } from './routes/_authenticated/testes/prompts'
import { Route as AuthenticatedTestesCenariosRouteImport } from './routes/_authenticated/testes/cenarios'

const SubmeterRoute = SubmeterRouteImport.update({
  id: '/submeter',
  path: '/submeter',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusProjetosRoute = MeusProjetosRouteImport.update({
  id: '/meus-projetos',
  path: '/meus-projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FaqRoute,
} as any)
const ProjetoIdRoute = ProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarIdRoute = EditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestigadorRoute =
  AuthenticatedInvestigadorRouteImport.update({
    id: '/investigador',
    path: '/investigador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFluxosRoute = AuthenticatedFluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspeciaisRoute = AuthenticatedEspeciaisRouteImport.update({
  id: '/especiais',
  path: '/especiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailLegadosRoute =
  AuthenticatedEmailLegadosRouteImport.update({
    id: '/email-legados',
    path: '/email-legados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesPendentesRoute =
  AuthenticatedAprovacoesPendentesRouteImport.update({
    id: '/aprovacoes-pendentes',
    path: '/aprovacoes-pendentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAglutinacaoRoute =
  AuthenticatedAglutinacaoRouteImport.update({
    id: '/aglutinacao',
    path: '/aglutinacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestesRouteRoute =
  AuthenticatedTestesRouteRouteImport.update({
    id: '/testes',
    path: '/testes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const FaqCategoriaIndexRoute = FaqCategoriaIndexRouteImport.update({
  id: '/$categoria/',
  path: '/$categoria/',
  getParentRoute: () => FaqRoute,
} as any)
const AuthenticatedTestesIndexRoute =
  AuthenticatedTestesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTestesRouteRoute,
  } as any)
const FaqCategoriaItemRoute = FaqCategoriaItemRouteImport.update({
  id: '/$categoria/$item',
  path: '/$categoria/$item',
  getParentRoute: () => FaqRoute,
} as any)
const AuthenticatedTestesPromptsRoute =
  AuthenticatedTestesPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedTestesRouteRoute,
  } as any)
const AuthenticatedTestesCenariosRoute =
  AuthenticatedTestesCenariosRouteImport.update({
    id: '/cenarios',
    path: '/cenarios',
    getParentRoute: () => AuthenticatedTestesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRouteWithChildren
  '/meus-projetos': typeof MeusProjetosRoute
  '/submeter': typeof SubmeterRoute
  '/testes': typeof AuthenticatedTestesRouteRouteWithChildren
  '/aglutinacao': typeof AuthenticatedAglutinacaoRoute
  '/aprovacoes-pendentes': typeof AuthenticatedAprovacoesPendentesRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-legados': typeof AuthenticatedEmailLegadosRoute
  '/especiais': typeof AuthenticatedEspeciaisRoute
  '/fluxos': typeof AuthenticatedFluxosRoute
  '/investigador': typeof AuthenticatedInvestigadorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/editar/$id': typeof EditarIdRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/faq/': typeof FaqIndexRoute
  '/testes/cenarios': typeof AuthenticatedTestesCenariosRoute
  '/testes/prompts': typeof AuthenticatedTestesPromptsRoute
  '/faq/$categoria/$item': typeof FaqCategoriaItemRoute
  '/testes/': typeof AuthenticatedTestesIndexRoute
  '/faq/$categoria/': typeof FaqCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/auth': typeof AuthRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/submeter': typeof SubmeterRoute
  '/aglutinacao': typeof AuthenticatedAglutinacaoRoute
  '/aprovacoes-pendentes': typeof AuthenticatedAprovacoesPendentesRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-legados': typeof AuthenticatedEmailLegadosRoute
  '/especiais': typeof AuthenticatedEspeciaisRoute
  '/fluxos': typeof AuthenticatedFluxosRoute
  '/investigador': typeof AuthenticatedInvestigadorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/editar/$id': typeof EditarIdRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/faq': typeof FaqIndexRoute
  '/testes/cenarios': typeof AuthenticatedTestesCenariosRoute
  '/testes/prompts': typeof AuthenticatedTestesPromptsRoute
  '/faq/$categoria/$item': typeof FaqCategoriaItemRoute
  '/testes': typeof AuthenticatedTestesIndexRoute
  '/faq/$categoria': typeof FaqCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRouteWithChildren
  '/meus-projetos': typeof MeusProjetosRoute
  '/submeter': typeof SubmeterRoute
  '/_authenticated/testes': typeof AuthenticatedTestesRouteRouteWithChildren
  '/_authenticated/aglutinacao': typeof AuthenticatedAglutinacaoRoute
  '/_authenticated/aprovacoes-pendentes': typeof AuthenticatedAprovacoesPendentesRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-legados': typeof AuthenticatedEmailLegadosRoute
  '/_authenticated/especiais': typeof AuthenticatedEspeciaisRoute
  '/_authenticated/fluxos': typeof AuthenticatedFluxosRoute
  '/_authenticated/investigador': typeof AuthenticatedInvestigadorRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/editar/$id': typeof EditarIdRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/faq/': typeof FaqIndexRoute
  '/_authenticated/testes/cenarios': typeof AuthenticatedTestesCenariosRoute
  '/_authenticated/testes/prompts': typeof AuthenticatedTestesPromptsRoute
  '/faq/$categoria/$item': typeof FaqCategoriaItemRoute
  '/_authenticated/testes/': typeof AuthenticatedTestesIndexRoute
  '/faq/$categoria/': typeof FaqCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovacoes'
    | '/auth'
    | '/faq'
    | '/meus-projetos'
    | '/submeter'
    | '/testes'
    | '/aglutinacao'
    | '/aprovacoes-pendentes'
    | '/areas'
    | '/dashboard'
    | '/email-legados'
    | '/especiais'
    | '/fluxos'
    | '/investigador'
    | '/usuarios'
    | '/editar/$id'
    | '/projeto/$id'
    | '/faq/'
    | '/testes/cenarios'
    | '/testes/prompts'
    | '/faq/$categoria/$item'
    | '/testes/'
    | '/faq/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprovacoes'
    | '/auth'
    | '/meus-projetos'
    | '/submeter'
    | '/aglutinacao'
    | '/aprovacoes-pendentes'
    | '/areas'
    | '/dashboard'
    | '/email-legados'
    | '/especiais'
    | '/fluxos'
    | '/investigador'
    | '/usuarios'
    | '/editar/$id'
    | '/projeto/$id'
    | '/faq'
    | '/testes/cenarios'
    | '/testes/prompts'
    | '/faq/$categoria/$item'
    | '/testes'
    | '/faq/$categoria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aprovacoes'
    | '/auth'
    | '/faq'
    | '/meus-projetos'
    | '/submeter'
    | '/_authenticated/testes'
    | '/_authenticated/aglutinacao'
    | '/_authenticated/aprovacoes-pendentes'
    | '/_authenticated/areas'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-legados'
    | '/_authenticated/especiais'
    | '/_authenticated/fluxos'
    | '/_authenticated/investigador'
    | '/_authenticated/usuarios'
    | '/editar/$id'
    | '/projeto/$id'
    | '/faq/'
    | '/_authenticated/testes/cenarios'
    | '/_authenticated/testes/prompts'
    | '/faq/$categoria/$item'
    | '/_authenticated/testes/'
    | '/faq/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AprovacoesRoute: typeof AprovacoesRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRouteWithChildren
  MeusProjetosRoute: typeof MeusProjetosRoute
  SubmeterRoute: typeof SubmeterRoute
  EditarIdRoute: typeof EditarIdRoute
  ProjetoIdRoute: typeof ProjetoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submeter': {
      id: '/submeter'
      path: '/submeter'
      fullPath: '/submeter'
      preLoaderRoute: typeof SubmeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-projetos': {
      id: '/meus-projetos'
      path: '/meus-projetos'
      fullPath: '/meus-projetos'
      preLoaderRoute: typeof MeusProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof FaqRoute
    }
    '/projeto/$id': {
      id: '/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof ProjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$id': {
      id: '/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof EditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigador': {
      id: '/_authenticated/investigador'
      path: '/investigador'
      fullPath: '/investigador'
      preLoaderRoute: typeof AuthenticatedInvestigadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxos': {
      id: '/_authenticated/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof AuthenticatedFluxosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/especiais': {
      id: '/_authenticated/especiais'
      path: '/especiais'
      fullPath: '/especiais'
      preLoaderRoute: typeof AuthenticatedEspeciaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-legados': {
      id: '/_authenticated/email-legados'
      path: '/email-legados'
      fullPath: '/email-legados'
      preLoaderRoute: typeof AuthenticatedEmailLegadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes-pendentes': {
      id: '/_authenticated/aprovacoes-pendentes'
      path: '/aprovacoes-pendentes'
      fullPath: '/aprovacoes-pendentes'
      preLoaderRoute: typeof AuthenticatedAprovacoesPendentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aglutinacao': {
      id: '/_authenticated/aglutinacao'
      path: '/aglutinacao'
      fullPath: '/aglutinacao'
      preLoaderRoute: typeof AuthenticatedAglutinacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/testes': {
      id: '/_authenticated/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof AuthenticatedTestesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/faq/$categoria/': {
      id: '/faq/$categoria/'
      path: '/$categoria'
      fullPath: '/faq/$categoria/'
      preLoaderRoute: typeof FaqCategoriaIndexRouteImport
      parentRoute: typeof FaqRoute
    }
    '/_authenticated/testes/': {
      id: '/_authenticated/testes/'
      path: '/'
      fullPath: '/testes/'
      preLoaderRoute: typeof AuthenticatedTestesIndexRouteImport
      parentRoute: typeof AuthenticatedTestesRouteRoute
    }
    '/faq/$categoria/$item': {
      id: '/faq/$categoria/$item'
      path: '/$categoria/$item'
      fullPath: '/faq/$categoria/$item'
      preLoaderRoute: typeof FaqCategoriaItemRouteImport
      parentRoute: typeof FaqRoute
    }
    '/_authenticated/testes/prompts': {
      id: '/_authenticated/testes/prompts'
      path: '/prompts'
      fullPath: '/testes/prompts'
      preLoaderRoute: typeof AuthenticatedTestesPromptsRouteImport
      parentRoute: typeof AuthenticatedTestesRouteRoute
    }
    '/_authenticated/testes/cenarios': {
      id: '/_authenticated/testes/cenarios'
      path: '/cenarios'
      fullPath: '/testes/cenarios'
      preLoaderRoute: typeof AuthenticatedTestesCenariosRouteImport
      parentRoute: typeof AuthenticatedTestesRouteRoute
    }
  }
}

interface AuthenticatedTestesRouteRouteChildren {
  AuthenticatedTestesCenariosRoute: typeof AuthenticatedTestesCenariosRoute
  AuthenticatedTestesPromptsRoute: typeof AuthenticatedTestesPromptsRoute
  AuthenticatedTestesIndexRoute: typeof AuthenticatedTestesIndexRoute
}

const AuthenticatedTestesRouteRouteChildren: AuthenticatedTestesRouteRouteChildren =
  {
    AuthenticatedTestesCenariosRoute: AuthenticatedTestesCenariosRoute,
    AuthenticatedTestesPromptsRoute: AuthenticatedTestesPromptsRoute,
    AuthenticatedTestesIndexRoute: AuthenticatedTestesIndexRoute,
  }

const AuthenticatedTestesRouteRouteWithChildren =
  AuthenticatedTestesRouteRoute._addFileChildren(
    AuthenticatedTestesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTestesRouteRoute: typeof AuthenticatedTestesRouteRouteWithChildren
  AuthenticatedAglutinacaoRoute: typeof AuthenticatedAglutinacaoRoute
  AuthenticatedAprovacoesPendentesRoute: typeof AuthenticatedAprovacoesPendentesRoute
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailLegadosRoute: typeof AuthenticatedEmailLegadosRoute
  AuthenticatedEspeciaisRoute: typeof AuthenticatedEspeciaisRoute
  AuthenticatedFluxosRoute: typeof AuthenticatedFluxosRoute
  AuthenticatedInvestigadorRoute: typeof AuthenticatedInvestigadorRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTestesRouteRoute: AuthenticatedTestesRouteRouteWithChildren,
  AuthenticatedAglutinacaoRoute: AuthenticatedAglutinacaoRoute,
  AuthenticatedAprovacoesPendentesRoute: AuthenticatedAprovacoesPendentesRoute,
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailLegadosRoute: AuthenticatedEmailLegadosRoute,
  AuthenticatedEspeciaisRoute: AuthenticatedEspeciaisRoute,
  AuthenticatedFluxosRoute: AuthenticatedFluxosRoute,
  AuthenticatedInvestigadorRoute: AuthenticatedInvestigadorRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FaqRouteChildren {
  FaqIndexRoute: typeof FaqIndexRoute
  FaqCategoriaItemRoute: typeof FaqCategoriaItemRoute
  FaqCategoriaIndexRoute: typeof FaqCategoriaIndexRoute
}

const FaqRouteChildren: FaqRouteChildren = {
  FaqIndexRoute: FaqIndexRoute,
  FaqCategoriaItemRoute: FaqCategoriaItemRoute,
  FaqCategoriaIndexRoute: FaqCategoriaIndexRoute,
}

const FaqRouteWithChildren = FaqRoute._addFileChildren(FaqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AprovacoesRoute: AprovacoesRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRouteWithChildren,
  MeusProjetosRoute: MeusProjetosRoute,
  SubmeterRoute: SubmeterRoute,
  EditarIdRoute: EditarIdRoute,
  ProjetoIdRoute: ProjetoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
