/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmeterRouteImport } from './routes/submeter'
import { Route as MeusProjetosRouteImport } from './routes/meus-projetos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetoIdRouteImport } from './routes/projeto.$id'
import { Route as EditarIdRouteImport } from './routes/editar.$id'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedInvestigadorRouteImport } from './routes/_authenticated/investigador'
import { Route as AuthenticatedEmailLegadosRouteImport } from './routes/_authenticated/email-legados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedTestesRouteRouteImport } from './routes/_authenticated/testes/route'
import { Route as AuthenticatedTestesIndexRouteImport } from './routes/_authenticated/testes/index'
import { Route as AuthenticatedTestesPromptsRouteImport } from './routes/_authenticated/testes/prompts'
import { Route as AuthenticatedTestesCenariosRouteImport } from './routes/_authenticated/testes/cenarios'

const SubmeterRoute = SubmeterRouteImport.update({
  id: '/submeter',
  path: '/submeter',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusProjetosRoute = MeusProjetosRouteImport.update({
  id: '/meus-projetos',
  path: '/meus-projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoIdRoute = ProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarIdRoute = EditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestigadorRoute =
  AuthenticatedInvestigadorRouteImport.update({
    id: '/investigador',
    path: '/investigador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailLegadosRoute =
  AuthenticatedEmailLegadosRouteImport.update({
    id: '/email-legados',
    path: '/email-legados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestesRouteRoute =
  AuthenticatedTestesRouteRouteImport.update({
    id: '/testes',
    path: '/testes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestesIndexRoute =
  AuthenticatedTestesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTestesRouteRoute,
  } as any)
const AuthenticatedTestesPromptsRoute =
  AuthenticatedTestesPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedTestesRouteRoute,
  } as any)
const AuthenticatedTestesCenariosRoute =
  AuthenticatedTestesCenariosRouteImport.update({
    id: '/cenarios',
    path: '/cenarios',
    getParentRoute: () => AuthenticatedTestesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/submeter': typeof SubmeterRoute
  '/testes': typeof AuthenticatedTestesRouteRouteWithChildren
  '/areas': typeof AuthenticatedAreasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-legados': typeof AuthenticatedEmailLegadosRoute
  '/investigador': typeof AuthenticatedInvestigadorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/editar/$id': typeof EditarIdRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/testes/cenarios': typeof AuthenticatedTestesCenariosRoute
  '/testes/prompts': typeof AuthenticatedTestesPromptsRoute
  '/testes/': typeof AuthenticatedTestesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/submeter': typeof SubmeterRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-legados': typeof AuthenticatedEmailLegadosRoute
  '/investigador': typeof AuthenticatedInvestigadorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/editar/$id': typeof EditarIdRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/testes/cenarios': typeof AuthenticatedTestesCenariosRoute
  '/testes/prompts': typeof AuthenticatedTestesPromptsRoute
  '/testes': typeof AuthenticatedTestesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/submeter': typeof SubmeterRoute
  '/_authenticated/testes': typeof AuthenticatedTestesRouteRouteWithChildren
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-legados': typeof AuthenticatedEmailLegadosRoute
  '/_authenticated/investigador': typeof AuthenticatedInvestigadorRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/editar/$id': typeof EditarIdRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/_authenticated/testes/cenarios': typeof AuthenticatedTestesCenariosRoute
  '/_authenticated/testes/prompts': typeof AuthenticatedTestesPromptsRoute
  '/_authenticated/testes/': typeof AuthenticatedTestesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/meus-projetos'
    | '/submeter'
    | '/testes'
    | '/areas'
    | '/dashboard'
    | '/email-legados'
    | '/investigador'
    | '/usuarios'
    | '/editar/$id'
    | '/projeto/$id'
    | '/testes/cenarios'
    | '/testes/prompts'
    | '/testes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/meus-projetos'
    | '/submeter'
    | '/areas'
    | '/dashboard'
    | '/email-legados'
    | '/investigador'
    | '/usuarios'
    | '/editar/$id'
    | '/projeto/$id'
    | '/testes/cenarios'
    | '/testes/prompts'
    | '/testes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/meus-projetos'
    | '/submeter'
    | '/_authenticated/testes'
    | '/_authenticated/areas'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-legados'
    | '/_authenticated/investigador'
    | '/_authenticated/usuarios'
    | '/editar/$id'
    | '/projeto/$id'
    | '/_authenticated/testes/cenarios'
    | '/_authenticated/testes/prompts'
    | '/_authenticated/testes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MeusProjetosRoute: typeof MeusProjetosRoute
  SubmeterRoute: typeof SubmeterRoute
  EditarIdRoute: typeof EditarIdRoute
  ProjetoIdRoute: typeof ProjetoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submeter': {
      id: '/submeter'
      path: '/submeter'
      fullPath: '/submeter'
      preLoaderRoute: typeof SubmeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-projetos': {
      id: '/meus-projetos'
      path: '/meus-projetos'
      fullPath: '/meus-projetos'
      preLoaderRoute: typeof MeusProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto/$id': {
      id: '/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof ProjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$id': {
      id: '/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof EditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigador': {
      id: '/_authenticated/investigador'
      path: '/investigador'
      fullPath: '/investigador'
      preLoaderRoute: typeof AuthenticatedInvestigadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-legados': {
      id: '/_authenticated/email-legados'
      path: '/email-legados'
      fullPath: '/email-legados'
      preLoaderRoute: typeof AuthenticatedEmailLegadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/testes': {
      id: '/_authenticated/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof AuthenticatedTestesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/testes/': {
      id: '/_authenticated/testes/'
      path: '/'
      fullPath: '/testes/'
      preLoaderRoute: typeof AuthenticatedTestesIndexRouteImport
      parentRoute: typeof AuthenticatedTestesRouteRoute
    }
    '/_authenticated/testes/prompts': {
      id: '/_authenticated/testes/prompts'
      path: '/prompts'
      fullPath: '/testes/prompts'
      preLoaderRoute: typeof AuthenticatedTestesPromptsRouteImport
      parentRoute: typeof AuthenticatedTestesRouteRoute
    }
    '/_authenticated/testes/cenarios': {
      id: '/_authenticated/testes/cenarios'
      path: '/cenarios'
      fullPath: '/testes/cenarios'
      preLoaderRoute: typeof AuthenticatedTestesCenariosRouteImport
      parentRoute: typeof AuthenticatedTestesRouteRoute
    }
  }
}

interface AuthenticatedTestesRouteRouteChildren {
  AuthenticatedTestesCenariosRoute: typeof AuthenticatedTestesCenariosRoute
  AuthenticatedTestesPromptsRoute: typeof AuthenticatedTestesPromptsRoute
  AuthenticatedTestesIndexRoute: typeof AuthenticatedTestesIndexRoute
}

const AuthenticatedTestesRouteRouteChildren: AuthenticatedTestesRouteRouteChildren =
  {
    AuthenticatedTestesCenariosRoute: AuthenticatedTestesCenariosRoute,
    AuthenticatedTestesPromptsRoute: AuthenticatedTestesPromptsRoute,
    AuthenticatedTestesIndexRoute: AuthenticatedTestesIndexRoute,
  }

const AuthenticatedTestesRouteRouteWithChildren =
  AuthenticatedTestesRouteRoute._addFileChildren(
    AuthenticatedTestesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTestesRouteRoute: typeof AuthenticatedTestesRouteRouteWithChildren
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailLegadosRoute: typeof AuthenticatedEmailLegadosRoute
  AuthenticatedInvestigadorRoute: typeof AuthenticatedInvestigadorRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTestesRouteRoute: AuthenticatedTestesRouteRouteWithChildren,
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailLegadosRoute: AuthenticatedEmailLegadosRoute,
  AuthenticatedInvestigadorRoute: AuthenticatedInvestigadorRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MeusProjetosRoute: MeusProjetosRoute,
  SubmeterRoute: SubmeterRoute,
  EditarIdRoute: EditarIdRoute,
  ProjetoIdRoute: ProjetoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
